### ISSUE TITLE
Fresh Windows 11 install, program starts and stops during pc startup

### ISSUE THREAD

**Issue by duceduc** [hass-agent/HASS.Agent#91] opened 2024-05-10 00:38 UTC
**Describe the bug**
Hass.Agent starts up and immediate shut down right after during windows startup. I can see the icon in taskbar for a few seconds and disappears right after. 

Also, the notification test popup does not work. Log says `reason: Disabled For User`. Not sure what I need to set in windows.

**Expected behavior**
Hass.agent should startup and stays connected during pc startup.

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output):
``` 
Edition Windows 11 Pro
Version 23H2
Installed on ‎5/‎3/‎2024
OS build 22631.3527
Experience Windows Feature Experience Pack 1000.22700.1003.0
```

 - Windows' UI language: English
 - HASS.Agent version: 2.0.1 (forked)

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Logs**
*Hass.Agent Log*
```
2024-05-10 04:15:44.048 +09:00 [INF] [MAIN] HASS.Agent version: 2.0.1
2024-05-10 04:15:44.053 +09:00 [INF] [SETTINGS] Config storage path: C:\Users\Duc\AppData\Local\HASS.Agent\Client\config
2024-05-10 04:15:44.126 +09:00 [INF] [SETTINGS] Configuration loaded
2024-05-10 04:15:44.129 +09:00 [INF] [LOCALIZATION] Selected UI culture: [en] English
2024-05-10 04:15:44.324 +09:00 [INF] [RADIOMGR] Ready
2024-05-10 04:15:46.361 +09:00 [INF] [INTERNALSENSORS] Ready
2024-05-10 04:15:49.004 +09:00 [ERR] [VIRTDESKT] Error initializing Virtual Desktop Manager, your Windows version may be unsupported
2024-05-10 04:15:49.026 +09:00 [INF] [SETTINGS_QUICKACTIONS] Loaded 1 entities
2024-05-10 04:15:49.039 +09:00 [INF] [SETTINGS_COMMANDS] Loaded 2 entities
2024-05-10 04:15:49.040 +09:00 [INF] [SETTINGS_SENSORS] Config not found, no entities loaded
2024-05-10 04:15:49.043 +09:00 [INF] [HOTKEY] Completed bind for global quickaction hotkey
2024-05-10 04:15:49.044 +09:00 [INF] [HOTKEY] Completed bind for 1 individual quickaction hotkeys
2024-05-10 04:15:49.076 +09:00 [INF] [LOCALAPI] Disabled
2024-05-10 04:15:49.076 +09:00 [INF] [MQTT] Identifying as device: DESKTOP-3L5PA48
2024-05-10 04:15:49.102 +09:00 [INF] [MQTT] Connecting ..
2024-05-10 04:15:49.151 +09:00 [INF] [SERVICE] Local install path: C:\Program Files\HASS.Agent\Service\
2024-05-10 04:15:49.169 +09:00 [WRN] [NOTIFIER] Showing notifications might fail, reason: DisabledForUser
2024-05-10 04:15:49.171 +09:00 [INF] [MQTT] Connected
2024-05-10 04:15:49.172 +09:00 [INF] [MEDIA] Ready
2024-05-10 04:15:49.209 +09:00 [INF] [NOTIFIER] Ready
2024-05-10 04:15:49.247 +09:00 [INF] [HASS_API] Home Assistant version: 2024.4.4
2024-05-10 04:15:49.546 +09:00 [INF] [HASS_API] System connected with http://192.168.1.20:8123
2024-05-10 04:15:51.117 +09:00 [INF] [MQTT] Initial registration completed
2024-05-10 04:15:53.632 +09:00 [FTL] [PROGRAM] Specified cast is not valid.
System.InvalidCastException: Specified cast is not valid.
   at WindowsDesktop.Interop.IServiceProvider.QueryService(Guid& guidService, Guid& riid)
   at WindowsDesktop.Interop.ComInterfaceAssembly.CreateInstance(Type type, Nullable`1 guidService)
   at WindowsDesktop.Interop.ComInterfaceAssembly.CreateInstance(String comInterfaceName, Guid clsid)
   at WindowsDesktop.Interop.ComWrapperBase`1..ctor(ComInterfaceAssembly assembly, Guid clsid)
   at WindowsDesktop.Interop.Build22621.VirtualDesktopManagerInternal..ctor(ComInterfaceAssembly assembly, ComWrapperFactory factory)
   at WindowsDesktop.Interop.Build22621.VirtualDesktopProvider22621.InitializeCore(ComInterfaceAssembly assembly)
   at WindowsDesktop.Interop.VirtualDesktopProvider.Initialize(ComInterfaceAssembly assembly)
   at WindowsDesktop.VirtualDesktop.InitializeCore()
   at WindowsDesktop.VirtualDesktop.HandleExplorerRestarted()
   at WindowsDesktop.VirtualDesktop.<>c.<.cctor>b__70_0()
   at WindowsDesktop.Utils.ExplorerRestartListenerWindow.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at Interop.User32.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(ApplicationContext context)
   at HASS.Agent.Program.Main(String[] args) in D:\a\HASS.Agent\HASS.Agent\src\HASS.Agent\HASS.Agent\Program.cs:line 102
2024-05-10 04:22:01.580 +09:00 [INF] [MAIN] HASS.Agent version: 2.0.1
2024-05-10 04:22:01.585 +09:00 [INF] [SETTINGS] Config storage path: C:\Users\Duc\AppData\Local\HASS.Agent\Client\config
2024-05-10 04:22:01.658 +09:00 [INF] [SETTINGS] Configuration loaded
2024-05-10 04:22:01.660 +09:00 [INF] [LOCALIZATION] Selected UI culture: [en] English
2024-05-10 04:22:01.845 +09:00 [INF] [RADIOMGR] Ready
2024-05-10 04:22:03.881 +09:00 [INF] [INTERNALSENSORS] Ready
2024-05-10 04:22:06.498 +09:00 [ERR] [VIRTDESKT] Error initializing Virtual Desktop Manager, your Windows version may be unsupported
2024-05-10 04:22:06.522 +09:00 [INF] [SETTINGS_QUICKACTIONS] Loaded 1 entities
2024-05-10 04:22:06.536 +09:00 [INF] [SETTINGS_COMMANDS] Loaded 2 entities
2024-05-10 04:22:06.537 +09:00 [INF] [SETTINGS_SENSORS] Config not found, no entities loaded
2024-05-10 04:22:06.540 +09:00 [INF] [HOTKEY] Completed bind for global quickaction hotkey
2024-05-10 04:22:06.540 +09:00 [INF] [HOTKEY] Completed bind for 1 individual quickaction hotkeys
2024-05-10 04:22:06.575 +09:00 [INF] [LOCALAPI] Disabled
2024-05-10 04:22:06.575 +09:00 [INF] [MQTT] Identifying as device: DESKTOP-3L5PA48
2024-05-10 04:22:06.600 +09:00 [INF] [MQTT] Connecting ..
2024-05-10 04:22:06.624 +09:00 [INF] [MEDIA] Ready
2024-05-10 04:22:06.649 +09:00 [INF] [SERVICE] Local install path: C:\Program Files\HASS.Agent\Service\
2024-05-10 04:22:06.662 +09:00 [WRN] [NOTIFIER] Showing notifications might fail, reason: DisabledForUser
2024-05-10 04:22:06.666 +09:00 [INF] [MQTT] Connected
2024-05-10 04:22:06.688 +09:00 [INF] [NOTIFIER] Ready
2024-05-10 04:22:06.767 +09:00 [INF] [HASS_API] Home Assistant version: 2024.4.4
2024-05-10 04:22:07.052 +09:00 [INF] [HASS_API] System connected with http://192.168.1.20:8123
2024-05-10 04:22:08.612 +09:00 [INF] [MQTT] Initial registration completed
2024-05-10 04:22:20.799 +09:00 [INF] [HASS_API] [switch.desktop_3l5pa48_launchurl] Performing action: turn_on
2024-05-10 04:22:20.808 +09:00 [INF] [HASS_API] [switch.desktop_3l5pa48_launchurl] Action completed: turn_on
2024-05-10 05:00:30.268 +09:00 [INF] [NOTIFIER] Attempting to show test notification ..
2024-05-10 05:00:30.284 +09:00 [INF] [NOTIFIER] Test notification attempt completed
2024-05-10 07:33:36.395 +09:00 [INF] [SYSTEMSTATE] Session ending: system shutting down
2024-05-10 07:33:36.397 +09:00 [INF] [SYSTEM] Application shutting down
2024-05-10 07:33:36.405 +09:00 [INF] [MQTT] Disconnected
2024-05-10 07:33:36.412 +09:00 [INF] [SYSTEMSTATE] Session ending: system shutting down
2024-05-10 07:33:36.426 +09:00 [ERR] [SYSTEM] Error shutting down nicely: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
2024-05-10 16:43:14.974 +09:00 [INF] [MAIN] HASS.Agent version: 2.0.1
2024-05-10 16:43:14.979 +09:00 [INF] [SETTINGS] Config storage path: C:\Users\Duc\AppData\Local\HASS.Agent\Client\config
2024-05-10 16:43:15.054 +09:00 [INF] [SETTINGS] Configuration loaded
2024-05-10 16:43:15.057 +09:00 [INF] [LOCALIZATION] Selected UI culture: [en] English
2024-05-10 16:43:15.252 +09:00 [INF] [RADIOMGR] Ready
2024-05-10 16:43:17.280 +09:00 [INF] [INTERNALSENSORS] Ready
2024-05-10 16:43:19.944 +09:00 [ERR] [VIRTDESKT] Error initializing Virtual Desktop Manager, your Windows version may be unsupported
2024-05-10 16:43:19.967 +09:00 [INF] [SETTINGS_QUICKACTIONS] Loaded 1 entities
2024-05-10 16:43:19.984 +09:00 [INF] [SETTINGS_COMMANDS] Loaded 2 entities
2024-05-10 16:43:19.985 +09:00 [INF] [SETTINGS_SENSORS] Config not found, no entities loaded
2024-05-10 16:43:19.988 +09:00 [INF] [HOTKEY] Completed bind for global quickaction hotkey
2024-05-10 16:43:19.989 +09:00 [INF] [HOTKEY] Completed bind for 1 individual quickaction hotkeys
2024-05-10 16:43:20.021 +09:00 [INF] [LOCALAPI] Disabled
2024-05-10 16:43:20.021 +09:00 [INF] [MQTT] Identifying as device: DESKTOP-3L5PA48
2024-05-10 16:43:20.045 +09:00 [INF] [MQTT] Connecting ..
2024-05-10 16:43:20.092 +09:00 [INF] [SERVICE] Local install path: C:\Program Files\HASS.Agent\Service\
2024-05-10 16:43:20.107 +09:00 [INF] [MEDIA] Ready
2024-05-10 16:43:20.107 +09:00 [INF] [MQTT] Connected
2024-05-10 16:43:20.108 +09:00 [WRN] [NOTIFIER] Showing notifications might fail, reason: DisabledForUser
2024-05-10 16:43:20.127 +09:00 [INF] [HASS_API] Home Assistant version: 2024.4.4
2024-05-10 16:43:20.144 +09:00 [INF] [NOTIFIER] Ready
2024-05-10 16:43:20.451 +09:00 [INF] [HASS_API] System connected with http://192.168.1.20:8123
2024-05-10 16:43:22.064 +09:00 [INF] [MQTT] Initial registration completed
2024-05-10 16:43:27.933 +09:00 [FTL] [PROGRAM] Specified cast is not valid.
System.InvalidCastException: Specified cast is not valid.
   at WindowsDesktop.Interop.IServiceProvider.QueryService(Guid& guidService, Guid& riid)
   at WindowsDesktop.Interop.ComInterfaceAssembly.CreateInstance(Type type, Nullable`1 guidService)
   at WindowsDesktop.Interop.ComInterfaceAssembly.CreateInstance(String comInterfaceName, Guid clsid)
   at WindowsDesktop.Interop.ComWrapperBase`1..ctor(ComInterfaceAssembly assembly, Guid clsid)
   at WindowsDesktop.Interop.Build22621.VirtualDesktopManagerInternal..ctor(ComInterfaceAssembly assembly, ComWrapperFactory factory)
   at WindowsDesktop.Interop.Build22621.VirtualDesktopProvider22621.InitializeCore(ComInterfaceAssembly assembly)
   at WindowsDesktop.Interop.VirtualDesktopProvider.Initialize(ComInterfaceAssembly assembly)
   at WindowsDesktop.VirtualDesktop.InitializeCore()
   at WindowsDesktop.VirtualDesktop.HandleExplorerRestarted()
   at WindowsDesktop.VirtualDesktop.<>c.<.cctor>b__70_0()
   at WindowsDesktop.Utils.ExplorerRestartListenerWindow.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at Interop.User32.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(ApplicationContext context)
   at HASS.Agent.Program.Main(String[] args) in D:\a\HASS.Agent\HASS.Agent\src\HASS.Agent\HASS.Agent\Program.cs:line 102
2024-05-10 17:16:35.375 +09:00 [INF] [MAIN] HASS.Agent version: 2.0.1
2024-05-10 17:16:35.380 +09:00 [INF] [SETTINGS] Config storage path: C:\Users\Duc\AppData\Local\HASS.Agent\Client\config
2024-05-10 17:16:35.454 +09:00 [INF] [SETTINGS] Configuration loaded
2024-05-10 17:16:35.456 +09:00 [INF] [LOCALIZATION] Selected UI culture: [en] English
2024-05-10 17:16:35.646 +09:00 [INF] [RADIOMGR] Ready
2024-05-10 17:16:37.681 +09:00 [INF] [INTERNALSENSORS] Ready
2024-05-10 17:16:40.375 +09:00 [ERR] [VIRTDESKT] Error initializing Virtual Desktop Manager, your Windows version may be unsupported
2024-05-10 17:16:40.396 +09:00 [INF] [SETTINGS_QUICKACTIONS] Loaded 1 entities
2024-05-10 17:16:40.409 +09:00 [INF] [SETTINGS_COMMANDS] Loaded 2 entities
2024-05-10 17:16:40.411 +09:00 [INF] [SETTINGS_SENSORS] Config not found, no entities loaded
2024-05-10 17:16:40.415 +09:00 [INF] [HOTKEY] Completed bind for global quickaction hotkey
2024-05-10 17:16:40.415 +09:00 [INF] [HOTKEY] Completed bind for 1 individual quickaction hotkeys
2024-05-10 17:16:40.454 +09:00 [INF] [LOCALAPI] Disabled
2024-05-10 17:16:40.482 +09:00 [INF] [MQTT] Identifying as device: DESKTOP-3L5PA48
2024-05-10 17:16:40.487 +09:00 [INF] [MQTT] Connecting ..
2024-05-10 17:16:40.515 +09:00 [INF] [MEDIA] Ready
2024-05-10 17:16:40.537 +09:00 [INF] [SERVICE] Local install path: C:\Program Files\HASS.Agent\Service\
2024-05-10 17:16:40.549 +09:00 [WRN] [NOTIFIER] Showing notifications might fail, reason: DisabledForUser
2024-05-10 17:16:40.552 +09:00 [INF] [MQTT] Connected
2024-05-10 17:16:40.552 +09:00 [INF] [HASS_API] Home Assistant version: 2024.4.4
2024-05-10 17:16:40.577 +09:00 [INF] [NOTIFIER] Ready
2024-05-10 17:16:40.920 +09:00 [INF] [HASS_API] System connected with http://192.168.1.20:8123
2024-05-10 17:16:42.501 +09:00 [INF] [MQTT] Initial registration completed
2024-05-10 17:17:14.230 +09:00 [INF] [HASS_API] [switch.desktop_3l5pa48_launchurl] Performing action: turn_on
2024-05-10 17:17:14.239 +09:00 [INF] [HASS_API] [switch.desktop_3l5pa48_launchurl] Action completed: turn_on
```

*Satellite Log*
```
2024-05-10 04:15:31.604 +09:00 [INF] [MAIN] Version: 2.0.1.0
2024-05-10 04:15:31.622 +09:00 [INF] [MAIN] Service started, initializing ..
2024-05-10 04:15:31.685 +09:00 [INF] [MAIN] Running as a service, initializing lifetime manager
2024-05-10 04:15:31.709 +09:00 [INF] [LIFETIMEMANAGER] Initialized
2024-05-10 04:15:31.739 +09:00 [INF] [WORKER] Startup completed, commencing execution ..
2024-05-10 04:15:32.222 +09:00 [INF] [SETTINGS] Config storage path: C:\Program Files\HASS.Agent\Service\config
2024-05-10 04:15:32.298 +09:00 [INF] [SETTINGS] Configuration loaded
2024-05-10 04:15:32.302 +09:00 [INF] [SETTINGS] MQTT configuration loaded
2024-05-10 04:15:32.302 +09:00 [INF] [SETTINGS_COMMANDS] Config not found, no entities loaded
2024-05-10 04:15:32.303 +09:00 [INF] [SETTINGS_SENSORS] Config not found, no entities loaded
2024-05-10 04:15:32.305 +09:00 [INF] [MQTT] Identifying as device: DESKTOP-3L5PA48-satellite
2024-05-10 04:15:32.306 +09:00 [INF] Application started. Hosting environment: Production; Content root path: C:\Program Files\HASS.Agent\Service\
2024-05-10 04:15:32.318 +09:00 [INF] [MQTT] Connecting ..
2024-05-10 04:15:32.319 +09:00 [INF] [RPCMANAGER] Listening
2024-05-10 04:15:32.345 +09:00 [INF] [MQTT] Connected
2024-05-10 04:15:34.329 +09:00 [INF] [MQTT] Initial registration completed
2024-05-10 07:33:40.358 +09:00 [INF] [SYSTEMSTATE] Session ending: system shutting down
2024-05-10 07:33:40.359 +09:00 [INF] [SYSTEM] Service shutting down
2024-05-10 07:33:40.365 +09:00 [INF] [MQTT] Disconnected
2024-05-10 07:33:40.366 +09:00 [INF] [SYSTEM] Service shutdown complete
2024-05-10 07:33:40.643 +09:00 [INF] [WORKER] Halting ..
2024-05-10 07:33:40.673 +09:00 [INF] Application is shutting down...
2024-05-10 16:42:48.136 +09:00 [INF] [MAIN] Version: 2.0.1.0
2024-05-10 16:42:48.154 +09:00 [INF] [MAIN] Service started, initializing ..
2024-05-10 16:42:48.216 +09:00 [INF] [MAIN] Running as a service, initializing lifetime manager
2024-05-10 16:42:48.240 +09:00 [INF] [LIFETIMEMANAGER] Initialized
2024-05-10 16:42:48.271 +09:00 [INF] [WORKER] Startup completed, commencing execution ..
2024-05-10 16:42:48.791 +09:00 [INF] [SETTINGS] Config storage path: C:\Program Files\HASS.Agent\Service\config
2024-05-10 16:42:48.867 +09:00 [INF] [SETTINGS] Configuration loaded
2024-05-10 16:42:48.870 +09:00 [INF] [SETTINGS] MQTT configuration loaded
2024-05-10 16:42:48.871 +09:00 [INF] [SETTINGS_COMMANDS] Config not found, no entities loaded
2024-05-10 16:42:48.871 +09:00 [INF] [SETTINGS_SENSORS] Config not found, no entities loaded
2024-05-10 16:42:48.873 +09:00 [INF] [MQTT] Identifying as device: DESKTOP-3L5PA48-satellite
2024-05-10 16:42:48.875 +09:00 [INF] Application started. Hosting environment: Production; Content root path: C:\Program Files\HASS.Agent\Service\
2024-05-10 16:42:48.884 +09:00 [INF] [RPCMANAGER] Listening
2024-05-10 16:42:48.885 +09:00 [INF] [MQTT] Connecting ..
2024-05-10 16:42:48.911 +09:00 [INF] [MQTT] Connected
2024-05-10 16:42:50.892 +09:00 [INF] [MQTT] Initial registration completed
```

**Comment by amadeo-alex** [comment] 2024-05-10 09:51
Hello, please fill in the bug issue template as it will help us identify what's going on. Just with that vague description and without any kind of logs we cannot advise on anything.

**Comment by duceduc** [comment] 2024-05-10 10:09
Hi. Sorry. I have edited the post.

**Comment by amadeo-alex** [comment] 2024-05-10 11:05
Ok, that looks good :D
So, judging from the logs the initial crash is caused by the Virtual Desktop management library initialisation we're using. There was a bug that caused issues on some machines - they've fixed is some time ago - most likely this is it.

Could you please try this version https://github.com/hass-agent/HASS.Agent/releases/tag/2.1.0-beta1 ?
It includes fix for this that was released with https://github.com/hass-agent/HASS.Agent/releases/tag/2.0.2-beta2

If that won't help we'll do additional digging to find the root cause of the issue.

As for this, if after the update to 2.1.0-beta1 it'll still say:
``` reason: Disabled For User ```
I have Win10 so the exact "path" may be a bit different but please check: "Settings -> System ->Notification & Actions" and in there if the notifications are allowed at all and then below, if HASS.Agent itself can show them (should look something like this https://itechhacks.com/wp-content/uploads/2021/08/Notifications.png)

**Comment by duceduc** [comment] 2024-05-10 11:59
The [2.1.0-beta1](https://github.com/hass-agent/HASS.Agent/releases/tag/2.1.0-beta1) version seems to be working. Hass.agent stays running now. Will monitor it for a few days. The notification also is working after turning `on` the notification in Windows setting.

**Closed** 2024-06-16 21:10 UTC
Labels: bug, info
