### ISSUE TITLE
Bug: Windows_software_updates is already used by [ComputerName]

### ISSUE THREAD

**Issue by ebonzl** [hass-agent/HASS.Agent#111] opened 2024-07-03 00:50 UTC
Please make sure that the issue you're planning to report is not already registered :)

----

The WindowsUpdates satelite sensor is not generating/using a unique id for the attributes: WindowsUpdates_driver_updates_pending, WindowsUpdates_software_updates_pending, WindowsUpdates_driver_updates, and WindowsUpdates_software_updates.
If you have the agent on multiple endpoints, there is a conflict in HomeAssistant which is logged as:

024-07-03 12:45:00.086 ERROR (MainThread) [homeassistant.components.sensor] Platform mqtt does not generate unique IDs. ID Windows_software_updates is already used by sensor.[Computer1]_windows_software_updates - ignoring sensor.[Computer2]_windows_software_updates

**To Reproduce**
1. Add more than one computer device using Hass Agent with identical sensors configured in Satelite Service configuration pointing to the same instance of Home Assistant

**Expected behavior**
WindowsUpdates type sensors should generate uniqueID, as other sensors do in the agent

 - Windows' UI language: English US
 - HASS.Agent version: 2.0.1

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [ ] Problem occurs in HASS.Agent
 - [x] Problem occurs in Satellite Service

**Comment by amadeo-alex** [comment] 2024-07-03 17:46
Thank you for reporting but it's duplicate of https://github.com/hass-agent/HASS.Agent/issues/89

**Closed by amadeo-alex** 2024-07-03 17:46 UTC
Labels: bug
