### ISSUE TITLE
Bug: Media player entity generates error in HA

### ISSUE THREAD

**Issue by TheFaither** [hass-agent/HASS.Agent#174] opened 2024-10-03 17:05 UTC
**Describe the bug**
The media player entity is not generated inside HA, and an error is generated

I am here posting the log from HA

2024-10-03 18:54:56.021 WARNING (SyncWorker_8) [homeassistant.helpers.frame] Detected that custom integration 'hass_agent' calls device_registry.async_update_device from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#device_registryasync_update_device at custom_components/hass_agent/__init__.py, line 29: device_registry.async_get_or_create(, please report it to the author of the 'hass_agent' custom integration
2024-10-03 18:54:56.031 ERROR (SyncWorker_8) [homeassistant.util.logging] Exception in updated when handling msg on 'hass.agent/devices/HUNKAHUNKA': '{"serial_number":[...],"device":{"identifiers":"hass.agent-HUNKAHUNKA","manufacturer":"HASS.Agent Team","model":"Microsoft Windows NT 10.0.22631.0","name":"HUNKAHUNKA","sw_version":"2.1.0"},"apis":{"notifications" :true,"media_player":true}}'
Traceback (most recent call last):
  File "/config/custom_components/hass_agent/__init__.py", line 144, in updated
    update_device_info(hass, entry, payload)
  File "/config/custom_components/hass_agent/__init__.py", line 29, in update_device_info
    device_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 834, in async_get_or_create
    device = self.async_update_device(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 1066, in async_update_device
    self.hass.verify_event_loop_thread("device_registry.async_update_device")
  File "/usr/src/homeassistant/homeassistant/core.py", line 462, in verify_event_loop_thread
    frame.report_non_thread_safe_operation(what)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 229, in report_non_thread_safe_operation
    report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 163, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 201, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'hass_agent' calls device_registry.async_update_device from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#device_registryasync_update_device at custom_components/hass_agent/__init__.py, line 29: device_registry.async_get_or_create(. Please report it to the author of the 'hass_agent' custom integration.

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Comment by TheFaither** [comment] 2024-10-04 14:39
Duplicate, fixed by myself following 
https://github.com/LAB02-Research/HASS.Agent-Integration/issues/47#issuecomment-2090454867

**Comment by amadeo-alex** [comment] 2024-10-04 17:43
Hello, yup, duplicate of https://github.com/hass-agent/HASS.Agent-Integration/issues/2 and relates to the integration rather than HASS.Agent itself.
The fix will work for now but I'd recommend switching to the forked integration https://github.com/hass-agent/HASS.Agent-Integration/issues/2

**Closed by amadeo-alex** 2024-10-04 17:43 UTC
Labels: bug
